// Mocks generated by Mockito 5.4.6 from annotations
// in synlen/test/features/reader/data/txt_content_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:synlen/src/core/database/app_database.dart' as _i4;
import 'package:synlen/src/features/library/data/book_manifest_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BookManifestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookManifestRepository extends _i1.Mock
    implements _i2.BookManifestRepository {
  MockBookManifestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BookManifest?> getManifestByHash(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#getManifestByHash, [fileHash]),
            returnValue: _i3.Future<_i4.BookManifest?>.value(),
          )
          as _i3.Future<_i4.BookManifest?>);

  @override
  _i3.Future<_i5.Either<String, int>> saveManifest(
    _i4.BookManifest? manifest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveManifest, [manifest]),
            returnValue: _i3.Future<_i5.Either<String, int>>.value(
              _i6.dummyValue<_i5.Either<String, int>>(
                this,
                Invocation.method(#saveManifest, [manifest]),
              ),
            ),
          )
          as _i3.Future<_i5.Either<String, int>>);

  @override
  _i3.Future<_i5.Either<String, bool>> deleteManifestByHash(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#deleteManifestByHash, [fileHash]),
            returnValue: _i3.Future<_i5.Either<String, bool>>.value(
              _i6.dummyValue<_i5.Either<String, bool>>(
                this,
                Invocation.method(#deleteManifestByHash, [fileHash]),
              ),
            ),
          )
          as _i3.Future<_i5.Either<String, bool>>);
}
