// Mocks generated by Mockito 5.4.6 from annotations
// in synlen/test/features/reader/application/reader_session_factory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:synlen/src/features/library/application/book_queries.dart'
    as _i2;
import 'package:synlen/src/features/library/domain/book_manifest.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BookQueries].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookQueries extends _i1.Mock implements _i2.BookQueries {
  MockBookQueries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
    ({
      String author,
      double? chapterScrollPosition,
      String? coverPath,
      int currentChapterIndex,
      int direction,
      String? filePath,
      int id,
      String title,
      int totalChapters,
    })?
  >
  findBook(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#findBook, [fileHash]),
            returnValue:
                _i3.Future<
                  ({
                    String author,
                    double? chapterScrollPosition,
                    String? coverPath,
                    int currentChapterIndex,
                    int direction,
                    String? filePath,
                    int id,
                    String title,
                    int totalChapters,
                  })?
                >.value(),
          )
          as _i3.Future<
            ({
              String author,
              double? chapterScrollPosition,
              String? coverPath,
              int currentChapterIndex,
              int direction,
              String? filePath,
              int id,
              String title,
              int totalChapters,
            })?
          >);

  @override
  _i3.Future<({List<_i4.SpineItem> spine, List<_i4.TocItem> toc})?>
  findManifest(String? fileHash) =>
      (super.noSuchMethod(
            Invocation.method(#findManifest, [fileHash]),
            returnValue:
                _i3.Future<
                  ({List<_i4.SpineItem> spine, List<_i4.TocItem> toc})?
                >.value(),
          )
          as _i3.Future<({List<_i4.SpineItem> spine, List<_i4.TocItem> toc})?>);

  @override
  _i3.Future<void> saveProgress({
    required int? bookId,
    required int? chapterIndex,
    required double? progress,
    required double? scrollPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [], {
              #bookId: bookId,
              #chapterIndex: chapterIndex,
              #progress: progress,
              #scrollPosition: scrollPosition,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
